package com.example.banchanrenew.relation

class EssentialCons {
    fun getData(): List<EssentialIngredients> {
        return ArrayList(
            listOf(
                EssentialIngredients("브로콜리", "500", 412),
                EssentialIngredients("소고기", "50", 413),
                EssentialIngredients("고등어", "125", 414),
                EssentialIngredients("굴", "300", 415),
                EssentialIngredients("대구", "100", 416),
                EssentialIngredients("봄동", "50", 419),
                EssentialIngredients("양파", "160", 420),
                EssentialIngredients("상추", "20", 421),
                EssentialIngredients("우엉", "50", 422),
                EssentialIngredients("소고기", "75", 425),
                EssentialIngredients("고등어", "60", 427),
                EssentialIngredients("고등어", "125", 428),
                EssentialIngredients("갈치", "200", 429),
                EssentialIngredients("갈치", "160", 430),
                EssentialIngredients("새우", "75", 431),
                EssentialIngredients("잔멸치", "25", 432),
                EssentialIngredients("햄", "10", 433),
                EssentialIngredients("우동면", "75", 435),
                EssentialIngredients("깻잎", "80", 437),
                EssentialIngredients("멸치", "25", 444),
                EssentialIngredients("파프리카", "90", 447),
                EssentialIngredients("돼지갈비", "500", 448),
                EssentialIngredients("시금치", "10", 449),
                EssentialIngredients("낙지", "50", 450),
                EssentialIngredients("새우", "100", 451),
                EssentialIngredients("시금치", "60", 454),
                EssentialIngredients("콩", "100", 457),
                EssentialIngredients("대하", "75", 461),
                EssentialIngredients("느타리버섯", "30", 469),
                EssentialIngredients("베이컨", "50", 412),
                EssentialIngredients("배추", "100", 415),
                EssentialIngredients("돼지고기", "50", 422),
                EssentialIngredients("낙지", "100", 425),
                EssentialIngredients("양파", "40", 433),
                EssentialIngredients("다진마늘", "2", 435),
                EssentialIngredients("두부", "125", 444),
                EssentialIngredients("계란", "75", 449),
                EssentialIngredients("모시조개", "80", 450),
                EssentialIngredients("표고버섯", "24", 469),
                EssentialIngredients("치즈", "2", 433),
                EssentialIngredients("된장", "25", 444),
                EssentialIngredients("팽이버섯", "15", 469),
                EssentialIngredients("당면", "25",3),
                EssentialIngredients("콩나물", "75",  4),
                EssentialIngredients("흑임자", "25", 7),
                EssentialIngredients("소고기", "50", 8),
                EssentialIngredients("밀가루", "100", 10),
                EssentialIngredients("국수", "50",  14),
                EssentialIngredients("숙주", "37",  16),
                EssentialIngredients("두부", "125",  18),
                EssentialIngredients("소고기", "30",  20),
                EssentialIngredients("미역", "15",  21),
                EssentialIngredients("미역", "15", 22),
                EssentialIngredients("오이", "80", 25),
                EssentialIngredients("도미", "150",  28),
                EssentialIngredients("소고기", "150", 29),
                EssentialIngredients("소고기", "100",  30),
                EssentialIngredients("팥", "100",  31),
                EssentialIngredients("죽순", "150",  32),
                EssentialIngredients("부추", "125",  33),
                EssentialIngredients("상추", "50",  34),
                EssentialIngredients("콩나물", "150", 35),
                EssentialIngredients("우엉", "100", 36),
                EssentialIngredients("두부", "250",  37),
                EssentialIngredients("잔멸치", "25",  38),
                EssentialIngredients("갈치", "100",  39),
                EssentialIngredients("닭고기", "160", 40),
                EssentialIngredients("두부", "250",  41),
                EssentialIngredients("칼국수면", "150",  42),
                EssentialIngredients("콩나물", "100",  43),
                EssentialIngredients("양배추", "100",  44),
                EssentialIngredients("마늘", "75",  45),
                EssentialIngredients("오징어", "120", 46),
                EssentialIngredients("대구", "150", 47),
                EssentialIngredients("갈비", "400", 48),
                EssentialIngredients("돼지고기", "200", 49),
                EssentialIngredients("소고기", "300", 50),
                EssentialIngredients("돼지고기", "150",  51),
                EssentialIngredients("홍합", "25", 52),
                EssentialIngredients("청국장", "50",  53),
                EssentialIngredients("순두부", "200", 54),
                EssentialIngredients("동태", "100",  55),
                EssentialIngredients("배추김치", "125",  56),
                EssentialIngredients("콩", "70",  57),
                EssentialIngredients("북어", "50",  58),
                EssentialIngredients("유부", "3", 59),
                EssentialIngredients("소고기", "5", 60),
                EssentialIngredients("해파리", "75",  61),
                EssentialIngredients("열무", "750", 62),
                EssentialIngredients("오이", "375",  64),
                EssentialIngredients("배추", "250",  65),
                EssentialIngredients("총각무", "375", 652),
                EssentialIngredients("무", "400",  66),
                EssentialIngredients("무", "1500",  67),
                EssentialIngredients("갓", "300", 68),
                EssentialIngredients("게", "300", 69),
                EssentialIngredients("돼지고기", "250",  70),
                EssentialIngredients("아귀", "325",  71),
                EssentialIngredients("조기", "30", 72),
                EssentialIngredients("명란", "2",  73),
                EssentialIngredients("우거지", "75",  74),
                EssentialIngredients("소고기", "200", 75),
                EssentialIngredients("낙지", "100",  77),
                EssentialIngredients("선지", "100",  78),
                EssentialIngredients("콩나물", "75", 79),
                EssentialIngredients("소고기", "100",  80),
                EssentialIngredients("소(잡뼈)", "75",  81),
                EssentialIngredients("도가니", "1",  82),
                EssentialIngredients("소고기", "150",  83),
                EssentialIngredients("소고기", "200",  84),
                EssentialIngredients("부추", "125", 85),
                EssentialIngredients("실파", "250", 86),
                EssentialIngredients("배추", "2500", 87),
                EssentialIngredients("깻잎", "200", 88),
                EssentialIngredients("오이", "375", 89),
                EssentialIngredients("콩", "90", 90),
                EssentialIngredients("소고기", "100",  91),
                EssentialIngredients("연근", "75", 92),
                EssentialIngredients("실파", "125", 93),
                EssentialIngredients("오이", "75", 94),
                EssentialIngredients("냉이", "25",  95),
                EssentialIngredients("계란", "1", 96),
                EssentialIngredients("닭고기", "320", 97),
                EssentialIngredients("배추", "125", 98),
                EssentialIngredients("더덕", "50", 99),
                EssentialIngredients("감자", "120",  100),
                EssentialIngredients("마른오징어", "30", 101),
                EssentialIngredients("죽순", "15", 102),
                EssentialIngredients("애호박", "75", 103),
                EssentialIngredients("피망", "60",  104),
                EssentialIngredients("메주콩", "90",  105),
                EssentialIngredients("소고기", "125", 106),
                EssentialIngredients("부추", "125", 107),
                EssentialIngredients("돼지갈비", "150", 108),
                EssentialIngredients("참치", "40",  109),
                EssentialIngredients("꽁치통조림", "100",  110),
                EssentialIngredients("배추김치", "50",  111),
                EssentialIngredients("낙지", "100", 112),
                EssentialIngredients("두부", "125", 113),
                EssentialIngredients("계란", "50", 114),
                EssentialIngredients("양배추", "40",  115),
                EssentialIngredients("계란", "50",  116),
                EssentialIngredients("계란", "25",  117),
                EssentialIngredients("라면", "1", 118),
                EssentialIngredients("계란", "100",  119),
                EssentialIngredients("꽁치", "125", 120),
                EssentialIngredients("감자", "80", 121),
                EssentialIngredients("실파", "50", 122),
                EssentialIngredients("도토리묵", "75", 123),
                EssentialIngredients("고등어", "125", 124),
                EssentialIngredients("가지", "60",  125),
                EssentialIngredients("소고기", "200",  126),
                EssentialIngredients("소고기", "150", 127),
                EssentialIngredients("골뱅이통조림", "100",  128),
                EssentialIngredients("두부", "125", 129),
                EssentialIngredients("소고기", "150",  130),
                EssentialIngredients("스파게티면", "150",  131),
                EssentialIngredients("닭고기", "1000", 132),
                EssentialIngredients("소고기", "50", 133),
                EssentialIngredients("유부", "5",  134),
                EssentialIngredients("감자", "160", 135),
                EssentialIngredients("식빵", "1",  136),
                EssentialIngredients("소고기", "20", 137),
                EssentialIngredients("양상추", "25",  138),
                EssentialIngredients("콜리플라워", "100",  139),
                EssentialIngredients("사과", "120", 140),
                EssentialIngredients("연어", "80", 141),
                EssentialIngredients("시금치", "35", 142),
                EssentialIngredients("감자", "160",  143),
                EssentialIngredients("햄", "75",  144),
                EssentialIngredients("곱창", "150",  145),
                EssentialIngredients("아귀", "250",  146),
                EssentialIngredients("강력분", "150",  147),
                EssentialIngredients("돼지고기", "150",  148),
                EssentialIngredients("배추", "50",  149),
                EssentialIngredients("멥쌀", "800",  150),
                EssentialIngredients("녹두", "180",  151),
                EssentialIngredients("소고기","75", 152),
                EssentialIngredients("토란", "150",  153),
                EssentialIngredients("소고기", "50",  154),
                EssentialIngredients("고등어", "125",  155),
                EssentialIngredients("당면", "25",  156),
                EssentialIngredients("고추장", "4",  157),
                EssentialIngredients("배추김치", "125",  158),
                EssentialIngredients("닭고기", "250", 159),
                EssentialIngredients("오징어", "240",  160),
                EssentialIngredients("누룽지", "60",  161),
                EssentialIngredients("가래떡", "30", 162),
                EssentialIngredients("찬밥", "100", 163),
                EssentialIngredients("팥", "150", 164),
                EssentialIngredients("밀가루", "75",  165),
                EssentialIngredients("고구마줄기", "13", 166),
                EssentialIngredients("어묵", "60",  167),
                EssentialIngredients("가래떡", "250",  168),
                EssentialIngredients("멥쌀", "800", 169),
                EssentialIngredients("생강", "75",  170),
                EssentialIngredients("닭고기", "500", 171),
                EssentialIngredients("찹쌀", "450",  172),
                EssentialIngredients("두부", "250", 173),
                EssentialIngredients("소고기", "170",  174),
                EssentialIngredients("오징어", "120", 175),
                EssentialIngredients("떡국떡", "200", 176),
                EssentialIngredients("찹쌀", "180",  177),
                EssentialIngredients("콩나물", "250",  178),
                EssentialIngredients("케일", "3",  179),
                EssentialIngredients("달래", "25",  180),
                EssentialIngredients("쑥", "13",  181),
                EssentialIngredients("닭고기", "100",  182),
                EssentialIngredients("봄동", "75", 183),
                EssentialIngredients("배추김치", "170",  184),
                EssentialIngredients("옥수수", "48", 185),
                EssentialIngredients("양배추", "50", 186),
                EssentialIngredients("오징어", "120",  187),
                EssentialIngredients("오이", "160",  188),
                EssentialIngredients("멥쌀", "180",  189),
                EssentialIngredients("시금치", "150",  190),
                EssentialIngredients("배추김치", "123", 191),
                EssentialIngredients("찹쌀", "180",  192),
                EssentialIngredients("계란", "100", 193),
                EssentialIngredients("어묵", "40", 194),
                EssentialIngredients("모시조개", "40", 195),
                EssentialIngredients("일본된장(미소)", "20",  196),
                EssentialIngredients("새우", "35",  197),
                EssentialIngredients("잣", "50", 198),
                EssentialIngredients("고추", "300", 199),
                EssentialIngredients("생선살", "75", 200),
                EssentialIngredients("소고기", "100",  201),
                EssentialIngredients("마늘", "4", 202),
                EssentialIngredients("소고기", "100",  203),
                EssentialIngredients("스파게티면", "40", 204),
                EssentialIngredients("게", "300",  205),
                EssentialIngredients("양상추", "50",  206),
                EssentialIngredients("닭고기", "250", 207),
                EssentialIngredients("돼지고기", "100",  208),
                EssentialIngredients("우유", "500", 209),
                EssentialIngredients("닭고기", "320", 210),
                EssentialIngredients("밀가루", "100", 211),
                EssentialIngredients("돼지고기", "100", 212),
                EssentialIngredients("소고기", "100", 213),
                EssentialIngredients("오징어", "360",  214),
                EssentialIngredients("계란", "50",  215),
                EssentialIngredients("딸기", "400", 216),
                EssentialIngredients("사골", "250",  217),
                EssentialIngredients("감자", "150",  218),
                EssentialIngredients("배추김치", "50",  219),
                EssentialIngredients("오곡곡물", "180",  220),
                EssentialIngredients("오징어", "120", 221),
                EssentialIngredients("돼기고기", "75",  222),
                EssentialIngredients("돼지고기", "150",  223),
                EssentialIngredients("코다리", "340",  224),
                EssentialIngredients("만두피", "3", 226),
                EssentialIngredients("새우", "25",  227),
                EssentialIngredients("소고기", "45",  228),
                EssentialIngredients("두부", "50",  229),
                EssentialIngredients("홍차티백", "1",  230),
                EssentialIngredients("가지", "60",  231),
                EssentialIngredients("닭고기", "50",  232),
                EssentialIngredients("식용유", "120",  233),
                EssentialIngredients("생태", "400",  234),
                EssentialIngredients("두부", "60",  235),
                EssentialIngredients("두부", "250", 236),
                EssentialIngredients("배추김치", "250", 237),
                EssentialIngredients("홍합", "100",  238),
                EssentialIngredients("돼지갈비", "450", 239),
                EssentialIngredients("가래떡", "15", 240),
                EssentialIngredients("돼지고기", "150", 241),
                EssentialIngredients("배추", "500",  242),
                EssentialIngredients("배추", "2500", 243),
                EssentialIngredients("사골", "75",  244),
                EssentialIngredients("참치", "20",  245),
                EssentialIngredients("팥", "150",  246),
                EssentialIngredients("소고기", "75",  247),
                EssentialIngredients("잔멸치", "25",  248),
                EssentialIngredients("소고기", "40",  249),
                EssentialIngredients("바게트", "15",  250),
                EssentialIngredients("소면", "100", 251),
                EssentialIngredients("오징어", "60",252),
                EssentialIngredients("콩나물", "50",  253),
                EssentialIngredients("무", "25",  254),
                EssentialIngredients("닭다리", "1", 255),
                EssentialIngredients("밤", "10",  256),
                EssentialIngredients("콩나물", "25",  257),
                EssentialIngredients("가래떡", "100",  258),
                EssentialIngredients("두부", "125",  259),
                EssentialIngredients("밀가루", "50", 260),
                EssentialIngredients("밀가루", "75",  263),
                EssentialIngredients("달래", "50",  265),
                EssentialIngredients("달래", "250", 266),
                EssentialIngredients("두릅", "100",  267),
                EssentialIngredients("숙주", "50",  268),
                EssentialIngredients("참나물", "50", 269),
                EssentialIngredients("오징어", "120", 270),
                EssentialIngredients("닭고기", "250",  271),
                EssentialIngredients("배추김치", "1000",  272),
                EssentialIngredients("애호박", "75",  273),
                EssentialIngredients("해파리", "40",  274),
                EssentialIngredients("닭고기", "75", 275),
                EssentialIngredients("아스파라거스", "25",  276),
                EssentialIngredients("밀가루", "50",  277),
                EssentialIngredients("돼지고기", "50",  278),
                EssentialIngredients("풋마늘", "20",  279),
                EssentialIngredients("상추", "8", 280),
                EssentialIngredients("두부", "63",  281),
                EssentialIngredients("브로콜리", "100",  283),
                EssentialIngredients("오징어", "60",  284),
                EssentialIngredients("옥수수통조림", "75", 285),
                EssentialIngredients("꽁치통조림", "100",  286),
                EssentialIngredients("돼지고기", "300",  287),
                EssentialIngredients("가래떡", "125",  288),
                EssentialIngredients("배추김치", "123", 290),
                EssentialIngredients("육수용멸치", "13",  291),
                EssentialIngredients("감자", "80", 92),
                EssentialIngredients("코다리", "340", 293),
                EssentialIngredients("닭고기", "250", 294),
                EssentialIngredients("순대", "75", 295),
                EssentialIngredients("닭고기", "150",  296),
                EssentialIngredients("베이컨", "100", 297),
                EssentialIngredients("당면", "150",  300),
                EssentialIngredients("깻잎", "60", 302),
                EssentialIngredients("쌀국수", "125", 303),
                EssentialIngredients("라면", "1",  305),
                EssentialIngredients("고등어", "125",  306),
                EssentialIngredients("소고기", "37",  307),
                EssentialIngredients("바지락", "100", 308),
                EssentialIngredients("가지", "40",  309),
                EssentialIngredients("청국장", "24",  310),
                EssentialIngredients("밀가루", "25", 311),
                EssentialIngredients("소고기", "100",  312),
                EssentialIngredients("소고기", "200",  314),
                EssentialIngredients("돼지고기", "75",  315),
                EssentialIngredients("쌀국수", "15",  316),
                EssentialIngredients("파스타", "125",  317),
                EssentialIngredients("닭다리", "5",  318),
                EssentialIngredients("배추김치", "333", 319),
                EssentialIngredients("도라지", "50",  322),
                EssentialIngredients("찹쌀", "90",  324),
                EssentialIngredients("미역", "37",  325),
                EssentialIngredients("오징어", "120", 326),
                EssentialIngredients("대구", "750", 328),
                EssentialIngredients("소고기", "100", 329),
                EssentialIngredients("고추", "75",  330),
                EssentialIngredients("김", "4",  331),
                EssentialIngredients("닭다리", "75",  332),
                EssentialIngredients("감자", "150",  333),
                EssentialIngredients("바게트", "120", 334),
                EssentialIngredients("닭고기", "50",  335),
                EssentialIngredients("계란", "50", 336),
                EssentialIngredients("콩나물", "40",  337),
                EssentialIngredients("찹쌀", "200", 338),
                EssentialIngredients("상추", "5",  339),
                EssentialIngredients("호박", "10",  340),
                EssentialIngredients("꽁치", "125", 341),
                EssentialIngredients("오징어", "120", 342),
                EssentialIngredients("무", "100", 343),
                EssentialIngredients("다시마", "1",  344),
                EssentialIngredients("소고기", "200", 345),
                EssentialIngredients("파래", "25", 346),
                EssentialIngredients("단호박", "50", 347),
                EssentialIngredients("스파게티면", "100", 348),
                EssentialIngredients("라이스페이퍼", "4", 349),
                EssentialIngredients("무", "35", 350),
                EssentialIngredients("고등어", "125", 351),
                EssentialIngredients("두부", "125",  352),
                EssentialIngredients("고구마", "200", 353),
                EssentialIngredients("시금치", "15", 354),
                EssentialIngredients("돼지고기", "300", 355),
                EssentialIngredients("찹쌀가루", "80", 361),
                EssentialIngredients("냉동만두", "90",  362),
                EssentialIngredients("콩나물", "20", 363),
                EssentialIngredients("소고기", "30", 364),
                EssentialIngredients("새우", "180", 366),
                EssentialIngredients("소고기스톡", "300", 368),
                EssentialIngredients("소고기", "125", 369),
                EssentialIngredients("메밀국수", "75", 370),
                EssentialIngredients("소고기", "15", 371),
                EssentialIngredients("게", "300",  372),
                EssentialIngredients("해초", "30",  373),
                EssentialIngredients("감자", "40",  374),
                EssentialIngredients("장어", "60", 375),
                EssentialIngredients("장어", "10",  376),
                EssentialIngredients("돼지고기", "100", 378),
                EssentialIngredients("양배추", "10",  379),
                EssentialIngredients("오징어", "120",  380),
                EssentialIngredients("대추", "30", 381),
                EssentialIngredients("콩", "90", 383),
                EssentialIngredients("우묵", "50", 384),
                EssentialIngredients("표고버섯", "15", 385),
                EssentialIngredients("조기", "30", 387),
                EssentialIngredients("참치", "40", 388),
                EssentialIngredients("돼지고기", "150", 389),
                EssentialIngredients("가지", "60",  391),
                EssentialIngredients("골뱅이통조림", "200", 392),
                EssentialIngredients("닭고기", "25",  393),
                EssentialIngredients("어묵", "50", 394),
                EssentialIngredients("오징어", "120",  395),
                EssentialIngredients("가래떡", "60",  396),
                EssentialIngredients("배추김치", "250", 398),
                EssentialIngredients("오징어", "120", 399),
                EssentialIngredients("부추", "60",  400),
                EssentialIngredients("라면", "1",  401),
                EssentialIngredients("밀가루", "50", 402),
                EssentialIngredients("꽃게", "450", 404),
                EssentialIngredients("녹두", "90", 405),
                EssentialIngredients("돼지고기", "100", 406),
                EssentialIngredients("단호박", "75", 407),
                EssentialIngredients("양파", "400",  409),
                EssentialIngredients("닭고기", "250", 410),
                EssentialIngredients("돼지고기","25",  3),
                EssentialIngredients( "소고기","25" , 4),
                EssentialIngredients("카레가루","20", 8),
                EssentialIngredients("감자","80" , 10),
                EssentialIngredients("표고버섯","12",  14),
            EssentialIngredients( "만두피","10",  16),
            EssentialIngredients("소고기","25" , 18),
            EssentialIngredients("무","100" , 20),
            EssentialIngredients("소고기","37", 21),
            EssentialIngredients("감자","80", 28),
            EssentialIngredients("양송이버섯","40", 30),
            EssentialIngredients("밀가루","200", 31),
            EssentialIngredients("표고버섯","150", 32),
            EssentialIngredients("표고버섯","75", 33),
            EssentialIngredients("두부","125", 34),
            EssentialIngredients("토마토","150", 37),
            EssentialIngredients("꽈리고추","25", 38),
            EssentialIngredients("무","50", 39),
            EssentialIngredients("다시마","1", 41),
            EssentialIngredients("팥","225", 42),
            EssentialIngredients("소고기","25", 43),
            EssentialIngredients("소고기","75", 44),
            EssentialIngredients("간장","25", 45),
            EssentialIngredients("무","200", 50),
            EssentialIngredients("새우젓","8", 51),
            EssentialIngredients("소고기","25", 53),
            EssentialIngredients("무","75", 55),
            EssentialIngredients("대파","10", 56),
            EssentialIngredients("돼지고기","50", 57),
            EssentialIngredients("콩나물","10", 58),
            EssentialIngredients("표고버섯","8", 60),
            EssentialIngredients("게맛살","100", 61),
            EssentialIngredients("부추","125", 64),
            EssentialIngredients("미나리","8", 65),
            EssentialIngredients("굴","50", 66),
            EssentialIngredients("고추","130", 67),
            EssentialIngredients("감자","160", 70),
            EssentialIngredients("콩나물","25", 71),
            EssentialIngredients("소고기","15", 73),
            EssentialIngredients("배추","50", 74),
            EssentialIngredients("배추","20", 75),
            EssentialIngredients("새우","30", 77),
            EssentialIngredients("우거지","25", 78),
            EssentialIngredients("양","150", 80),
            EssentialIngredients("양지머리","150", 81),
            EssentialIngredients("소고기","100", 82),
            EssentialIngredients("무","100", 83),
            EssentialIngredients("무","100", 84),
            EssentialIngredients("계란","1", 91),
            EssentialIngredients("굴","25",  93),
            EssentialIngredients("모시조개","50",  95),
            EssentialIngredients("멸치","25",  100),
            EssentialIngredients("소고기","15", 102),
            EssentialIngredients( "돼지고기","150",  104),
            EssentialIngredients("계란","100", 105),
            EssentialIngredients( "오징어","96",  109),
            EssentialIngredients("무","15", 110),
            EssentialIngredients("소고기","25",  111),
            EssentialIngredients("배추김치","250", 113),
            EssentialIngredients("소고기","50",  115),
            EssentialIngredients( "돼지고기","100", 116),
            EssentialIngredients( "돼지고기","50", 117),
            EssentialIngredients("배추김치","50", 118),
            EssentialIngredients("국수","50", 119),
            EssentialIngredients("양파","20", 122),
            EssentialIngredients("청포묵","75", 123),
            EssentialIngredients("새우","10", 125),
            EssentialIngredients("팽이버섯","100",  126),
            EssentialIngredients("오이","25",  128),
            EssentialIngredients("배","75",130),
            EssentialIngredients("생크림","75",  131),
            EssentialIngredients("계란","50", 134),
            EssentialIngredients("소고기","100", 136),
            EssentialIngredients( "느타리버섯","25",  137),
            EssentialIngredients("닭고기","50",  138),
            EssentialIngredients("오징어","120",  139),
            EssentialIngredients("자몽","180",  140),
            EssentialIngredients("양송이버섯","30",  142),
            EssentialIngredients("토마토","320", 143),
            EssentialIngredients("소세지","40",  144),
            EssentialIngredients("양","75",  145),
            EssentialIngredients("미더덕","60",  146),
            EssentialIngredients( "설탕","16", 147),
            EssentialIngredients("고추","60", 148),
            EssentialIngredients("무","50",  149),
            EssentialIngredients("소금","16", 150),
            EssentialIngredients("돼지고기","50", 151),
            EssentialIngredients("표고버섯","24", 152),
            EssentialIngredients("소고기","100",  153),
            EssentialIngredients("목이버섯","3",  154),
            EssentialIngredients("무","135" , 155),
            EssentialIngredients("소고기","25",  156),
            EssentialIngredients("된장","12", 157),
            EssentialIngredients("돼지고기","40",  158),
        EssentialIngredients("소고기","35", 160),
        EssentialIngredients("표고버섯","16",  161),
        EssentialIngredients("버터","75",  165),
        EssentialIngredients("닭고기","50",  167),
        EssentialIngredients("소고기","50" , 168),
        EssentialIngredients("계피가루","25", 170),
        EssentialIngredients("멥쌀","450", 172),
        EssentialIngredients("소고기","50", 173),
        EssentialIngredients("두부","35", 174),
        EssentialIngredients("낙지","50",  175),
        EssentialIngredients("팥","50", 177),
        EssentialIngredients( "무","80" , 178),
        EssentialIngredients("치커리","3",  179),
        EssentialIngredients("두부","125",  180),
        EssentialIngredients("표고버섯","12",  181),
        EssentialIngredients("명란","1", 182),
        EssentialIngredients("바지락","50", 183),
        EssentialIngredients("감자","80",  184),
        EssentialIngredients("모시조개","100" , 186),
        EssentialIngredients("소고기","50" , 187),
        EssentialIngredients("양파","40", 188),
        EssentialIngredients("찹쌀","45" , 189),
        EssentialIngredients("말린새우","15",  190),
        EssentialIngredients("멥쌀","90", 192),
        EssentialIngredients("두부","25",  196),
        EssentialIngredients("만두피","6", 197),
        EssentialIngredients("새우","50", 200),
        EssentialIngredients("무","100" , 201),
        EssentialIngredients("명란","50", 202),
        EssentialIngredients("양","75", 203),
        EssentialIngredients("고추장","20", 204),
        EssentialIngredients("대하","100", 205),
        EssentialIngredients("표고버섯","100",  206),
        EssentialIngredients("깻잎","36", 208),
        EssentialIngredients("녹차분말","2",  211),
        EssentialIngredients("모짜렐라치즈","25", 212),
        EssentialIngredients("가래떡","150" , 213),
        EssentialIngredients("피망","120", 214),
        EssentialIngredients("두부","135", 215),
        EssentialIngredients("소고기","100" , 217),
        EssentialIngredients("밀가루","105",  218),
        EssentialIngredients("감자","80", 219),
        EssentialIngredients("상추","3",  220),
        EssentialIngredients( "오징어","60",  222),
        EssentialIngredients("부추","25", 223),
        EssentialIngredients("실파","10" , 224),
        EssentialIngredients("돼기고기","25",  226),
        EssentialIngredients( "오징어","13" , 227),
        EssentialIngredients("두부","250", 228),
        EssentialIngredients("치즈","1",  229),
        EssentialIngredients("계란","50", 230),
        EssentialIngredients("돼지고기","25",  231),
        EssentialIngredients("콘플레이크","80",  232),
        EssentialIngredients("고추","30", 233),
        EssentialIngredients("바지락","25", 234),
        EssentialIngredients("굴","50",  235),
        EssentialIngredients("돼지고기","25",  236),
        EssentialIngredients("소고기","25", 237),
        EssentialIngredients("대파","5",  238),
        EssentialIngredients("양파","80", 239),
        EssentialIngredients("고춧가루","4", 241),
        EssentialIngredients("실파","60" , 242),
        EssentialIngredients("무","200",  243),
        EssentialIngredients("소고기","50",  244),
        EssentialIngredients( "양파","10",  245),
        EssentialIngredients("설탕","200",  246),
        EssentialIngredients("낙지","100" , 247),
        EssentialIngredients("된장","1" , 248),
        EssentialIngredients("콩나물","25" , 249),
        EssentialIngredients("모짜렐라치즈","25",  250),
        EssentialIngredients("배추김치","50",  251),
        EssentialIngredients("계란","12",  252),
        EssentialIngredients( "소고기","25",  253),
        EssentialIngredients("어묵","50", 254),
        EssentialIngredients( "고구마","34",  256),
        EssentialIngredients("도라지","25",  257),
        EssentialIngredients("소고기","20" , 258),
        EssentialIngredients("소고기","40" , 259),
        EssentialIngredients("시금치즙","24",  263),
        EssentialIngredients("굴","40", 265),
        EssentialIngredients("된장","8",  267),
        EssentialIngredients("미나리","25", 268),
        EssentialIngredients("콩나물","75" , 271),
        EssentialIngredients("두부","125", 272),
        EssentialIngredients("두부","63" , 273),
        EssentialIngredients("새우","90",  274),
        EssentialIngredients("새우","50" , 276),
        EssentialIngredients("소고기","50",  277),
        EssentialIngredients("표고버섯","16" , 278),
        EssentialIngredients("오징어","120", 279),
        EssentialIngredients("계란","50" , 281),
        EssentialIngredients("우유","75",  283),
        EssentialIngredients("새우","15", 284),
        EssentialIngredients("배추김치","75", 286),
        EssentialIngredients("모짜렐라치즈","50", 287),
        EssentialIngredients("소고기","75" , 288),
        EssentialIngredients("소고기","5", 291),
        EssentialIngredients("생강즙","8", 296),
        EssentialIngredients( "느타리버섯","15",  300),
        EssentialIngredients("가래떡","15",  305),
        EssentialIngredients("배추김치","250", 306),
        EssentialIngredients("새우","13", 307),
        EssentialIngredients("소고기","33" , 309),
        EssentialIngredients("표고버섯","15", 310),
        EssentialIngredients("찹쌀가루","16",  311),
        EssentialIngredients("무순","13",  312),
        EssentialIngredients("새송이버섯","150", 314),
        EssentialIngredients("부추","50",  315),
        EssentialIngredients("돼지고기","10",  316),
        EssentialIngredients("표고버섯","75",  317),
        EssentialIngredients("대파","40",  318),
        EssentialIngredients("오징어","120", 322),
        EssentialIngredients("양송이버섯","32" , 324),
        EssentialIngredients("홍합","125",  325),
        EssentialIngredients("무","15",  328),
        EssentialIngredients("찹쌀가루","50",  329),
        EssentialIngredients("찹쌀가루","50",  330),
        EssentialIngredients("오징어","60", 331),
        EssentialIngredients( "소면","200",  332),
        EssentialIngredients("양파","30",  333),
        EssentialIngredients("죽순","5" , 335),
        EssentialIngredients( "오이","20", 337),
        EssentialIngredients("들깻잎","5",  339),
        EssentialIngredients("양파","10",  340),
        EssentialIngredients("새우","60",  344),
        EssentialIngredients("홍합","50",  348),
        EssentialIngredients("쌀국수","25",  349),
        EssentialIngredients("양배추","8" , 352),
        EssentialIngredients("양상추","15" , 362),
        EssentialIngredients("미나리","5", 363),
        EssentialIngredients("당근","25",  368),
        EssentialIngredients("바지락","15",  372),
        EssentialIngredients("미역","15" , 373),
        EssentialIngredients("양파","40",  374),
        EssentialIngredients("계란","125", 376),
        EssentialIngredients("우동면","120" , 379),
        EssentialIngredients("돼지고기","100", 380),
        EssentialIngredients( "깐밤","15",  381),
        EssentialIngredients("느타리버섯","15", 385),
        EssentialIngredients("양파","8", 388),
        EssentialIngredients("돼지고기","75" , 391),
        EssentialIngredients("해파리","30" , 393),
        EssentialIngredients("두부","125",  395),
        EssentialIngredients("소고기","25", 396),
        EssentialIngredients("참치","80", 398),
        EssentialIngredients("돼지고기","50", 400),
        EssentialIngredients("소고기","50", 401),
        EssentialIngredients("소고기","100" , 402),
        EssentialIngredients("만두피","15", 409),
        EssentialIngredients("미역","5",410),
                EssentialIngredients( "표고버섯","8", ,3),
                EssentialIngredients( "오이","20",  14),
                EssentialIngredients( "소고기","10", 16),
                EssentialIngredients("방울토마토","25", 28),
                EssentialIngredients("방울토마토","25", 30),
                EssentialIngredients("적양배추","50", 34),
                EssentialIngredients("바질","10", 37),
                EssentialIngredients("표고버섯","50", 43),
                EssentialIngredients("밤","20",44),
                EssentialIngredients("당근","50", 50),
                EssentialIngredients("무","50", 51),
                EssentialIngredients("무","40", 53),
                EssentialIngredients("배추","10", 57),
                EssentialIngredients("두부","65", 58),
                EssentialIngredients("멸치","4", 60),
                EssentialIngredients("오이","75", 61),
                EssentialIngredients("고추","13", 65),
                EssentialIngredients("갓","75", 67),
                EssentialIngredients("무","50", 73),
                EssentialIngredients("된장","16", 74),
                EssentialIngredients("팽이버섯","25", 75),
                EssentialIngredients("소고기","40", 77),
                EssentialIngredients("무","100", 80),
                EssentialIngredients("도가니","1",81),
                EssentialIngredients("당면","25", 83),
                EssentialIngredients( "홍합","25",  93),
                EssentialIngredients( "된장","12", 95),
                EssentialIngredients( "꽈리고추","10", 100),
                EssentialIngredients( "녹말가루","8", 104),
                EssentialIngredients( "문어","25", 109),
                EssentialIngredients( "표고버섯","20",  111),
                EssentialIngredients( "돼지고기","50", 115),
                EssentialIngredients( "표고버섯","16", 118),
                EssentialIngredients( "돼지고기","40",  122),
                EssentialIngredients( "당근","25",  126),
                EssentialIngredients( "양파","25", 128),
                EssentialIngredients("잣","3", 130),
                EssentialIngredients( "우유","100", 131),
                EssentialIngredients( "표고버섯","12",  , 137),
                EssentialIngredients( "수삼","20", 138),
                EssentialIngredients( "새우","120" , 139),
                EssentialIngredients( "샐러리","30", 140),
                EssentialIngredients( "베이컨","40", 142),
                EssentialIngredients( "배추김치","500" , 144),
                EssentialIngredients( "미나리","30",  145),
                EssentialIngredients( "콩나물","150" , 146),
                EssentialIngredients( "무순","25", 148),
                EssentialIngredients( "소고기","15", 149),
                EssentialIngredients( "쑥","150",  150),
                EssentialIngredients( "숙주","50",  151),
                EssentialIngredients( "도라지","50",  152),
                EssentialIngredients( "무","100", 153),
                EssentialIngredients( "팽이버섯","20", 154),
                EssentialIngredients( "느타리버섯","200", 156),
                EssentialIngredients( "죽순","25",  158),
                EssentialIngredients( "두부","25",  160),
                EssentialIngredients( "죽순","16",  161),
                EssentialIngredients( "팥","75", 165),
                EssentialIngredients( "표고버섯","8" , 167),
                EssentialIngredients( "팥","300", 172),
                EssentialIngredients( "새우","60",  175),
                EssentialIngredients( "청경채","3",  179),
                EssentialIngredients( "표고버섯","8", 180),
                EssentialIngredients( "양송이버섯","13",  181),
                EssentialIngredients( "두부","65", 184),
                EssentialIngredients( "된장","24", 190),
                EssentialIngredients( "팥","40", 192),
                EssentialIngredients( "미역","5", 196),
                EssentialIngredients( "배추김치","25" , 200),
                EssentialIngredients( "곱창","75",  203),
                EssentialIngredients( "오징어","120",  205),
                EssentialIngredients( "부추","50",  206),
                EssentialIngredients( "소금","2", 211),
                EssentialIngredients( "우유","4", 215),
                EssentialIngredients( "계란","25", 218),
                EssentialIngredients( "밀가루","100",  219),
                EssentialIngredients( "깻잎","3",  220),
                EssentialIngredients( "모시조개","50",  222),
                EssentialIngredients( "양파","20",  223),
                EssentialIngredients( "두부","125",  226),
                EssentialIngredients( "방울토마토","10" , 229),
                EssentialIngredients( "카레가루","15", 232),
                EssentialIngredients( "무","25", 234),
                EssentialIngredients( "양송이버섯","8", 235),
                EssentialIngredients( "느타리버섯","25",  236),
                EssentialIngredients( "고추","6", 238),
                EssentialIngredients( "감자","80",  239),
                EssentialIngredients( "미나리","75",  243),
                EssentialIngredients( "우거지","50",  244),
                EssentialIngredients( "당근","13", 245),
                EssentialIngredients( "인절미","50",  246),
                EssentialIngredients( "배추김치","100" , 250),
                EssentialIngredients( "오이","40",  251),
                EssentialIngredients( "녹말가루","25", 252),
                EssentialIngredients( "느타리버섯","25" , 253),
                EssentialIngredients( "은행","6", 256),
                EssentialIngredients( "시금치","25", 257),
                EssentialIngredients( "당근즙","24" , 263),
                EssentialIngredients( "밀가루","50" , 265),
                EssentialIngredients( "실고추","8" , 267),
                EssentialIngredients( "돼지고기","150" , 272),
                EssentialIngredients( "쭈꾸미","10" , 274),
                EssentialIngredients( "배추","50", 277),
                EssentialIngredients( "생크림","25", 283),
                EssentialIngredients( "가래떡","15" , 284),
                EssentialIngredients( "소면","75", 291),
                EssentialIngredients( "팽이버섯","15",  300),
                EssentialIngredients( "어묵","15", 305),
                EssentialIngredients( "해삼","20" , 307),
                EssentialIngredients( "느타리버섯","35", 310),
                EssentialIngredients( "부추","50",  311),
                EssentialIngredients( "양배추","17", 312),
                EssentialIngredients( "잣","3" , 314),
                EssentialIngredients( "밀가루","75" , 315),
                EssentialIngredients( "숙주나물","15" , 316),
                EssentialIngredients( "느타리버섯","50",  317),
                EssentialIngredients( "고사리","50" , 318),
                EssentialIngredients( "참기름","4" , 325),
                EssentialIngredients( "콩나물","13",  328),
                EssentialIngredients( "무","15",  331),
                EssentialIngredients( "부추","25", 332),
                EssentialIngredients( "대파","15",  333),
                EssentialIngredients( "소고기","30" , 337),
                EssentialIngredients( "쑥갓","3",  339),
                EssentialIngredients( "두부","8" , 340),
                EssentialIngredients( "바지락","50",  344),
                EssentialIngredients( "오징어","60",  348),
                EssentialIngredients( "오징어","60" , 349),
                EssentialIngredients( "양파","40",  368),
                EssentialIngredients( "맛조개","20", 372),
                EssentialIngredients( "밀가루","16", 374),
                EssentialIngredients( "은행","6",  381),
                EssentialIngredients( "새송이버섯","15",  385),
                EssentialIngredients( "당근","10", 388),
                EssentialIngredients( "모시조개","40",  395),
                EssentialIngredients( "밀가루","50" , 410),
                EssentialIngredients( "부추","8" ,3),
                EssentialIngredients( "부추","40" , 14),
                EssentialIngredients("양파","20", 44),
                EssentialIngredients("표고버섯","50",50),
                EssentialIngredients("단무지","4", 60),
                EssentialIngredients("표고버섯","12", 75),
                EssentialIngredients("사골","100", 81),
                EssentialIngredients( "모시조개","25",  93),
                EssentialIngredients( "새우","60", 109),

                EssentialIngredients( "도라지","25", 111),
                EssentialIngredients( "콩나물","15", "햄","8", "게맛살","25", 118),
                EssentialIngredients( "부추","75", 126),

                EssentialIngredients( "양송이","12", "목이버섯","6", "팽이버섯","15" , 137),
                EssentialIngredients( "오이","80", "딸기","40", 140),
                EssentialIngredients( "쑥갓","3", 145),

                EssentialIngredients( "대추","50", 150),
                EssentialIngredients( "느타리버섯","100" , 151),
                EssentialIngredients( "당근","100", "오이","80", 152),

                EssentialIngredients( "양송이버섯","15" , 158),

                EssentialIngredients( "당면","15", 160),
                EssentialIngredients( "새우","50", 161),
                EssentialIngredients( "모시조개","75", "당면","25" , 175),
                EssentialIngredients( "겨자잎","3" , 179),
                EssentialIngredients( "느타리버섯","13", 181),
                EssentialIngredients( "고사리","50", 203),
                EssentialIngredients( "모시조개","200" , 205),
                EssentialIngredients( "고구마","100", 206),

                EssentialIngredients( "계란","25" , 219),
                EssentialIngredients( "치커리","3" , 220),

                EssentialIngredients( "홍합","100", 222),
                EssentialIngredients( "배추","100", 223),
                EssentialIngredients( "숙주","25", "느타리버섯","25", "표고버섯","16",226),


                EssentialIngredients( "다진마늘","3", 231),
                EssentialIngredients( "표고버섯","16", "팽이버섯","25", 236),

                EssentialIngredients( "당근","50", "무","50" , 239),
                EssentialIngredients( "생굴","50", "낙지","25", 243),
                EssentialIngredients( "대파","10", 244),

                EssentialIngredients( "양배추","10", "깻잎","40", "상추","20", 251),
                EssentialIngredients( "옥수수","12", 252),
                EssentialIngredients( "대추","20", 256),
                EssentialIngredients( "고사리","25" , 257),

                EssentialIngredients( "목이버섯","15" , 300),
                EssentialIngredients( "고추","60", "오징어","60", 311),
                EssentialIngredients( "당근","13" , 312),
                EssentialIngredients( "양송이버섯","50", 317),
                EssentialIngredients( "고추","24", "미나리","10", 328),
                EssentialIngredients( "케일","5" , 339),

                EssentialIngredients( "칼국수면","60" , 344),

                EssentialIngredients( "새우","45", "홀토마토","50" , 348),

                EssentialIngredients( "양파","40", "샐러리","2", "피망","30", "무","10" , 368),

                EssentialIngredients( "오징어","60" , 372),
                EssentialIngredients( "깻잎","24" , 374),

                EssentialIngredients( "느타리버섯","30", "옥수수통조림","170" , 381),

                EssentialIngredients( "소고기","15", "칼국수면","25" , 385),

                EssentialIngredients( "오이","10", "양상추","20" , 388),



                EssentialIngredients( "배추김치","15", 395),







                ))
    }
}